import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Outlet, Link, createRootRouteWithContext, useRouter, HeadContent, Scripts } from "@tanstack/react-router";
import { useEffect, type ReactNode } from "react";
import appCss from "../styles.css?url";
import { reportLovableError } from "../lib/lovable-error-reporting";
import { captureInitialAttribution, trackLeadEvent } from "../lib/leadTracking";
import { LeadCaptureWidget } from "../components/livefit/LeadCaptureWidget";
function NotFoundComponent(){return <div className="flex min-h-screen items-center justify-center bg-background px-4"><div className="max-w-md text-center"><h1 className="text-7xl font-bold text-foreground">404</h1><h2 className="mt-4 text-xl font-semibold text-foreground">Page not found</h2><p className="mt-2 text-sm text-muted-foreground">The page you're looking for doesn't exist or has been moved.</p><div className="mt-6"><Link to="/" className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">Go home</Link></div></div></div>}
function ErrorComponent({error,reset}:{error:Error;reset:()=>void}){console.error(error);const router=useRouter();useEffect(()=>{reportLovableError(error,{boundary:"tanstack_root_error_component"})},[error]);return <div className="flex min-h-screen items-center justify-center bg-background px-4"><div className="max-w-md text-center"><h1 className="text-xl font-semibold tracking-tight text-foreground">This page didn't load</h1><p className="mt-2 text-sm text-muted-foreground">Something went wrong on our end. You can try refreshing or head back home.</p><div className="mt-6 flex flex-wrap justify-center gap-2"><button onClick={()=>{router.invalidate();reset()}} className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">Try again</button><a href="/" className="inline-flex items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium text-foreground">Go home</a></div></div></div>}
function LeadTrackingListener(){useEffect(()=>{captureInitialAttribution();if(window.location.pathname!=="/")return;const handleClick=(event:MouseEvent)=>{const target=event.target as HTMLElement|null;const anchor=target?.closest("a") as HTMLAnchorElement|null;if(!anchor||anchor.dataset.trackLead==="handled")return;const href=anchor.getAttribute("href")||"";const eventType=href.startsWith("tel:")?"call_click":href.includes("wa.me/")?"whatsapp_click":href.includes("#assessment")||href==="/book-assessment"?"booking_cta_click":null;if(!eventType)return;const location=(anchor.dataset.ctaLocation||anchor.getAttribute("aria-label")||anchor.textContent||"CTA").trim().replace(/\s+/g," ").slice(0,120);void trackLeadEvent(eventType,"/",location)};document.addEventListener("click",handleClick,true);return()=>document.removeEventListener("click",handleClick,true)},[]);return null}
export const Route=createRootRouteWithContext<{queryClient:QueryClient}>()({head:()=>({meta:[{charSet:"utf-8"},{name:"viewport",content:"width=device-width, initial-scale=1"},{title:"Physiotherapy in Islamabad | LiveFit Physiotherapy"},{name:"description",content:"Expert physiotherapy in Islamabad for back pain, sciatica, disc bulge, spine problems and sports injuries. Book your assessment at LiveFit."},{property:"og:type",content:"website"},{property:"og:url",content:"https://livefitphysiotherapy.com/"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"stylesheet",href:appCss},{rel:"preconnect",href:"https://fonts.googleapis.com"},{rel:"preconnect",href:"https://fonts.gstatic.com",crossOrigin:"anonymous"},{rel:"stylesheet",href:"https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&family=Instrument+Serif:ital@0;1&display=swap"},{rel:"icon",type:"image/png",href:"/favicon.png"}],scripts:[{src:"https://www.googletagmanager.com/gtag/js?id=AW-18406446829",async:true},{children:`window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag('js',new Date());gtag('config','AW-18406446829');`}]}),shellComponent:RootShell,component:RootComponent,notFoundComponent:NotFoundComponent,errorComponent:ErrorComponent});
function RootShell({children}:{children:ReactNode}){return <html lang="en"><head><HeadContent/></head><body>{children}<Scripts/></body></html>}
function RootComponent(){const {queryClient}=Route.useRouteContext();return <QueryClientProvider client={queryClient}><LeadTrackingListener/><Outlet/><LeadCaptureWidget/></QueryClientProvider>}
