import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Phone, MapPin, Clock, ClipboardList, ArrowRight, Navigation, MessageCircle, Star, CheckCircle2 } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Header } from "@/components/livefit/Header";
import { trackPhoneConversion } from "@/lib/conversion";
import { trackCta } from "@/lib/track";
import { MAPS_URL, PHONE_DISPLAY, PHONE_TEL } from "@/components/livefit/data";
import logo from "@/assets/livefit-logo.jpg.asset.json";
import doctorAsset from "@/assets/doctor-livefit.png.asset.json";
import assessmentAsset from "@/assets/clinic-assessment.png.asset.json";
import consultAsset from "@/assets/clinic-consult.png.asset.json";
import treatmentAsset from "@/assets/clinic-treatment.png.asset.json";
import mobilityAsset from "@/assets/clinic-mobility.png.asset.json";
import frontAsset from "@/assets/clinic-signboard.webp.asset.json";
import backPainAsset from "@/assets/problem-back-pain.png.asset.json";
import sciaticaAsset from "@/assets/problem-sciatica.png.asset.json";
import discBulgeAsset from "@/assets/problem-disc-bulge.png.asset.json";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "Spine Physiotherapy in Islamabad | LiveFit Physiotherapy" },
      { name: "description", content: "LiveFit Physiotherapy in F-7 Markaz, Islamabad, led by Dr. Saad Sarfraz. Focused physiotherapy for back pain, sciatica and disc bulge. Assessment PKR 1,499." },
      { property: "og:title", content: "Spine Physiotherapy in Islamabad | LiveFit Physiotherapy" },
      { property: "og:description", content: "Dr. Saad Sarfraz provides spine-focused physiotherapy for back pain, sciatica and disc-related problems at LiveFit, Islamabad." },
      { property: "og:type", content: "website" },
      { property: "og:url", content: "https://livefitphysiotherapy.com/" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
    links: [{ rel: "canonical", href: "https://livefitphysiotherapy.com/" }],
    scripts: [{ type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "MedicalClinic", name: "LiveFit Physiotherapy", description: "Physiotherapy clinic in Islamabad focused on back pain, spine problems, sciatica and disc bulge.", telephone: "+92 332 3337337", url: "https://livefitphysiotherapy.com/", medicalSpecialty: "Physiotherapy", address: { "@type": "PostalAddress", streetAddress: "Suite # LG-04, Pakland Trade Centre, F-7 Markaz", addressLocality: "Islamabad", addressCountry: "PK" } }) }],
  }),
  component: Index,
});

const PRICE = "PKR 1,499";
const primary = "inline-flex items-center justify-center gap-2.5 rounded-full bg-primary px-6 py-4 text-[15px] font-semibold text-primary-foreground shadow-sm transition-all hover:-translate-y-0.5 hover:bg-charcoal hover:text-background";
const secondary = "inline-flex items-center justify-center gap-2.5 rounded-full border border-charcoal/20 bg-card px-6 py-4 text-[15px] font-semibold text-charcoal transition-all hover:border-charcoal hover:bg-charcoal hover:text-background";

const reviews = [
  ["Ifrah Babar", "a month ago", "It was good clean environment and satisfactory assessment, my father session is going great with them", "1 review · 6 photos"],
  ["Abdul Ghaffar", "2 months ago", "Visited the clinic and very satisfied with the services provided by dr Soma. She is very professional and kind she heard me with patience. She is very competent I would recommend her.", "2 reviews"],
  ["Laiba Siddiqui", "2 months ago", "I highly recommend LiveFit Physio! I came in with severe shoulder, neck, and back pain, and the experience has been amazing. The doctor is incredibly well-qualified, professional, and took the time to guide me through everything thoroughly.", "1 review"],
  ["Junaid Nadeem", "5 months ago", "I had a great experience, Dr.Saad did my complete and detailed examination. I was happy with the session he provided me with and how he guided me with my treatment protocol.", "2 reviews"],
  ["Namra Kainat", "2 months ago", "Had a great experience. I had Cervical stiffness and neck muscle tightness for almost a year and had no idea about about aftr the proper consultation the doctor diagnosed it", "4 reviews · 1 photo"],
  ["Md Ali", "5 months ago", "Extremely professional and trustworthy having a good knowledge and skill in filed. I would recommend livefit physiotherapy the physio to every one", "8 reviews"],
  ["Usama Muhammad Nadeem", "5 months ago", "Dr. Saad is a really passionate physiotherapist. Everyone coming here will be in good hands! ✨", "Local Guide · 15 reviews · 4 photos"],
  ["Maryam Nazakat", "4 months ago", "I came for back stiffness, they recommended dry cupping. My experience was great and I highly recommend this clinic", "4 reviews · 6 photos"],
  ["ameer Mukhtar", "3 months ago", "Dr Saad ko back pain k liye visit kya tha and in 6 session now I'm feeling very much better", "1 review"],
  ["Laiba Gul", "a month ago", "I visited for a consultation and was impressed with a care and the treatment I received.", "1 review"],
] as const;

const faqs = [
  ["What happens during the PKR 1,499 assessment?", "Dr. Saad assesses your symptoms, movement, functional limitations and relevant contributing factors. You receive professional guidance on the next appropriate steps based on your assessment."],
  ["Can I come if my back pain has been there for months?", "Yes. Persistent or recurring back pain is one of the main reasons people seek a proper physiotherapy assessment. The first step is understanding what may be contributing to your symptoms and movement limitations."],
  ["I have sciatica. Can physiotherapy help?", "Sciatica can have different causes and presentations. A physiotherapy assessment can help determine the appropriate approach for your symptoms and whether physiotherapy is suitable for you."],
  ["I have a disc bulge or slip disc on an MRI. What should I do?", "An MRI finding should be considered alongside your symptoms and physical assessment. Bring your reports if you have them so Dr. Saad can consider the full picture and guide you on appropriate next steps."],
  ["Do I need an MRI before my assessment?", "Not necessarily. If you already have an MRI or other relevant medical reports, bring them with you. Whether further investigation is appropriate depends on your individual presentation."],
  ["Where is LiveFit Physiotherapy located?", "LiveFit Physiotherapy is at Suite # LG-04, Pakland Trade Centre, F-7 Markaz, Islamabad."],
  ["How do I book?", "Use the Book Your Assessment button to submit your details, or call 0332 3337337. Our team can guide you through the booking process."],
];

function Eyebrow({ children }: { children: string }) { return <p className="eyebrow inline-flex rounded-full bg-accent px-4 py-2 text-accent-foreground">{children}</p>; }

function BookCTA({ className = "" }: { className?: string }) {
  const click = async (e: React.MouseEvent<HTMLAnchorElement>) => { e.preventDefault(); await trackCta("assessment_cta_click", window.location.pathname, "homepage_assessment_cta"); window.location.href = "/book-assessment"; };
  return <a data-track-lead="handled" href="/book-assessment" onClick={click} className={`${primary} ${className}`}><ClipboardList className="h-4 w-4" /> Book Your Assessment — {PRICE}</a>;
}

function Call({ className = "" }: { className?: string }) {
  return <a data-track-lead="handled" href={PHONE_TEL} onClick={async e => { e.preventDefault(); await trackCta("call_click", window.location.pathname, "homepage_call"); trackPhoneConversion(); window.location.href = PHONE_TEL; }} className={`${secondary} ${className}`}><Phone className="h-4 w-4" /> Call {PHONE_DISPLAY}</a>;
}

function ReviewCard({ review, index }: { review: readonly [string, string, string, string]; index: number }) {
  const [expanded, setExpanded] = useState(false); const [name, time, text, meta] = review;
  return <article className={`w-[84vw] shrink-0 snap-start border border-border bg-card p-6 shadow-[0_18px_50px_-34px_oklch(0.24_0.006_150_/_0.5)] sm:w-[420px] ${index % 4 === 0 ? "sm:mt-5" : ""} ${index % 4 === 2 ? "sm:-mt-3" : ""}`}>
    <div className="flex items-start justify-between gap-4"><div><p className="text-base font-semibold text-charcoal">{name}</p><p className="mt-1 text-xs text-muted-foreground">{time}</p></div><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-accent"><Star className="h-4 w-4 fill-primary text-primary" /></span></div>
    <div className="mt-4 flex gap-0.5 text-sm text-primary" aria-label="5 stars">★★★★★</div><p className={`mt-4 text-[15px] leading-7 text-charcoal-soft ${expanded ? "" : "line-clamp-5"}`}>&quot;{text}&quot;</p>
    {text.length > 210 && <button type="button" onClick={() => setExpanded(v => !v)} className="mt-2 text-sm font-semibold text-primary">{expanded ? "Show less" : "Read more"}</button>}
    <p className="mt-5 text-xs text-muted-foreground">{meta}</p><p className="mt-3 text-[11px] font-medium text-muted-foreground">Google review</p>
  </article>;
}

function ProblemCard({ number, title, body, image }: { number: string; title: string; body: string; image: string }) {
  return <article className="group relative min-h-[430px] overflow-hidden rounded-[2rem] bg-charcoal text-background"><img src={image} alt={title} loading="lazy" className="absolute inset-0 h-full w-full object-cover opacity-45 transition-transform duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-charcoal/60" /><div className="relative flex min-h-[430px] flex-col justify-between p-7 sm:p-8"><span className="font-display text-4xl text-primary">{number}</span><div><h3 className="font-display text-3xl">{title}</h3><p className="mt-3 max-w-sm text-sm leading-6 text-background/75">{body}</p><a href="#assessment" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-primary">See how we can help <ArrowRight className="h-4 w-4" /></a></div></div></article>;
}

function Index() {
  return <div id="top" className="min-h-screen overflow-x-hidden bg-background"><Header /><main className="pb-20 lg:pb-0">
    <section className="relative overflow-hidden border-b border-border"><div aria-hidden className="pointer-events-none absolute -right-40 -top-32 h-[600px] w-[600px] rounded-full bg-accent/70 blur-3xl" /><div className="relative mx-auto grid max-w-7xl items-center gap-10 px-5 py-8 sm:px-8 sm:py-12 lg:grid-cols-[1fr_.88fr] lg:gap-16 lg:py-16"><div className="order-2 lg:order-1"><Eyebrow>SPINE-FOCUSED PHYSIOTHERAPY • ISLAMABAD</Eyebrow><h1 className="mt-6 max-w-3xl font-display text-[clamp(2.7rem,7vw,5.4rem)] font-bold leading-[.94] tracking-tight">Back Pain, Sciatica or Disc Bulge <span className="text-primary">Holding You Back?</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-muted-foreground sm:text-lg">Get a professional physiotherapy assessment with Dr. Saad Sarfraz to understand your symptoms, movement limitations and the next appropriate step.</p><div id="assessment" className="mt-7 max-w-md rounded-[1.75rem] border border-border bg-card p-6 shadow-[0_24px_60px_-35px_oklch(0.24_0.006_150_/_0.45)] sm:p-7"><p className="eyebrow text-primary">Physiotherapy Assessment</p><p className="mt-2 font-display text-5xl font-bold text-charcoal sm:text-6xl">{PRICE}</p><div className="mt-5 grid gap-3 text-[15px] text-muted-foreground"><span className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-primary" /> Personalized Assessment</span><span className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-primary" /> Treatment Guidance</span><span className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-primary" /> Next-Step Plan</span></div><div className="mt-6 flex flex-col gap-3"><BookCTA /><Call /></div><p className="mt-4 text-sm text-muted-foreground">F-7 Markaz, Islamabad</p></div></div><div className="relative order-1 lg:order-2 lg:pl-4"><img src={doctorAsset.url} alt="Dr. Saad Sarfraz, Chief Physiotherapist at LiveFit Physiotherapy" width={1080} height={1440} className="aspect-[3/4] w-full rounded-[2rem] object-cover object-top shadow-[0_30px_70px_-28px_oklch(0.24_0.006_150_/_0.45)]" /><div className="absolute bottom-5 left-5 right-5 border border-border/70 bg-card/95 p-5 shadow-xl backdrop-blur sm:left-auto sm:w-[350px]"><p className="text-base font-semibold text-charcoal">Dr. Saad Sarfraz</p><p className="mt-1 text-sm font-semibold text-primary">Chief Physiotherapist · Spine Specialist</p><p className="mt-2 text-[13px] leading-6 text-muted-foreground">DPT (STMU) · MSPH (QAU)<br />COMT (UK) · CSMT (UK) · CKTP (USA)</p></div></div></div></section>

    <section id="conditions" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-28"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><Eyebrow>DOES THIS SOUND FAMILIAR?</Eyebrow><h2 className="mt-5 max-w-3xl font-display text-5xl leading-tight sm:text-6xl">Pain That Starts Affecting Everyday Life</h2></div><p className="max-w-lg text-base leading-7 text-muted-foreground">Focused assessment and rehabilitation for the spine problems people most commonly seek help for at LiveFit.</p></div><div className="mt-12 grid gap-5 md:grid-cols-3"><ProblemCard number="01" title="Back Pain" body="Pain, stiffness or difficulty moving that makes sitting, standing, walking or everyday tasks harder." image={backPainAsset.url} /><ProblemCard number="02" title="Sciatica" body="Back or leg symptoms that may interfere with walking, sitting, sleeping or staying active." image={sciaticaAsset.url} /><ProblemCard number="03" title="Disc Bulge / Slip Disc" body="A disc-related problem can leave you unsure what movements or treatment are appropriate for you." image={discBulgeAsset.url} /></div></section>

    <section className="border-y border-border bg-sand"><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 py-20 sm:px-8 lg:grid-cols-[.9fr_1.1fr] lg:py-24"><div><Eyebrow>WHEN PAIN BECOMES PART OF YOUR DAY</Eyebrow><h2 className="mt-5 max-w-2xl font-display text-5xl leading-tight sm:text-6xl">You shouldn&apos;t have to keep guessing what to do next.</h2><p className="mt-6 max-w-xl text-base leading-7 text-muted-foreground">Maybe you have tried rest, home exercises, pain medication or different advice. Maybe the pain keeps returning. A proper assessment can help you move from guessing to a clearer, individualized plan.</p><div className="mt-7 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-border bg-card p-5"><p className="font-semibold text-charcoal">Pain keeps coming back</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Understand what may be contributing to your symptoms instead of repeatedly managing flare-ups.</p></div><div className="rounded-2xl border border-border bg-card p-5"><p className="font-semibold text-charcoal">Movement feels limited</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Know which movements, exercises and next steps may be appropriate for your situation.</p></div></div></div><img src={assessmentAsset.url} alt="Physiotherapy assessment at LiveFit" loading="lazy" className="aspect-[4/3] w-full rounded-[2rem] object-cover shadow-[0_25px_60px_-35px_oklch(0.24_0.006_150_/_0.45)]" /></div></section>

    <section id="about" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-28"><div className="grid items-center gap-12 lg:grid-cols-[.78fr_1.22fr] lg:gap-16"><div><img src={doctorAsset.url} alt="Dr. Saad Sarfraz, Chief Physiotherapist and Spine Specialist" loading="lazy" className="aspect-[3/4] w-full rounded-[2rem] object-cover object-top" /></div><div><Eyebrow>MEET YOUR PHYSIOTHERAPIST</Eyebrow><h2 className="mt-5 font-display text-5xl sm:text-7xl">Dr. Saad Sarfraz</h2><p className="mt-3 text-lg font-semibold text-primary">Chief Physiotherapist · Spine Specialist</p><p className="mt-5 font-display text-2xl leading-tight text-charcoal sm:text-3xl">Spine-Focused Physiotherapy</p><div className="mt-6 grid gap-2 text-[15px] text-charcoal-soft sm:grid-cols-2"><span>DPT (STMU)</span><span>MSPH (QAU)</span><span>COMT (UK)</span><span>CSMT (UK)</span><span>CKTP (USA)</span></div><p className="mt-7 eyebrow text-primary">Focus: Back Pain · Sciatica · Disc Bulge</p><p className="mt-5 max-w-2xl text-base leading-7 text-muted-foreground">Dr. Saad Sarfraz provides personalized physiotherapy and rehabilitation for patients dealing with spine-related pain, back pain, sciatica, disc-related problems and movement limitations.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><BookCTA /><Call /></div></div></div></section>

    <section className="border-y border-border bg-charcoal text-background"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-24"><div className="max-w-3xl"><Eyebrow>YOUR ASSESSMENT IS THE FIRST STEP</Eyebrow><h2 className="mt-5 font-display text-5xl leading-tight sm:text-6xl">Understand the problem before deciding the plan.</h2><p className="mt-6 text-base leading-7 text-background/70">The goal of the assessment is not to give everyone the same treatment. It is to understand your presentation and determine an appropriate direction for care.</p></div><div className="mt-12 grid gap-4 md:grid-cols-4"><div className="rounded-2xl border border-background/10 bg-background/5 p-6"><span className="font-display text-3xl text-primary">01</span><h3 className="mt-8 font-semibold">Listen</h3><p className="mt-2 text-sm leading-6 text-background/65">Understand your symptoms, concerns and goals.</p></div><div className="rounded-2xl border border-background/10 bg-background/5 p-6"><span className="font-display text-3xl text-primary">02</span><h3 className="mt-8 font-semibold">Assess</h3><p className="mt-2 text-sm leading-6 text-background/65">Look at movement and relevant physical findings.</p></div><div className="rounded-2xl border border-background/10 bg-background/5 p-6"><span className="font-display text-3xl text-primary">03</span><h3 className="mt-8 font-semibold">Explain</h3><p className="mt-2 text-sm leading-6 text-background/65">Help you understand what the assessment suggests.</p></div><div className="rounded-2xl border border-background/10 bg-background/5 p-6"><span className="font-display text-3xl text-primary">04</span><h3 className="mt-8 font-semibold">Plan</h3><p className="mt-2 text-sm leading-6 text-background/65">Discuss appropriate next steps for your situation.</p></div></div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-28"><div className="grid items-center gap-10 lg:grid-cols-[1.05fr_.95fr]"><div><Eyebrow>START WITH A PROFESSIONAL ASSESSMENT</Eyebrow><h2 className="mt-5 max-w-3xl font-display text-5xl leading-tight sm:text-6xl">A clearer first step for your pain.</h2><p className="mt-6 max-w-2xl text-base leading-7 text-muted-foreground">If back pain, sciatica or a disc-related problem is affecting your daily life, start with an assessment rather than trying to figure everything out yourself.</p><ul className="mt-8 grid gap-4 text-[15px] text-charcoal-soft"><li className="flex gap-3"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-primary" /><span><strong className="text-charcoal">Personalized assessment</strong><br />Your symptoms and movement are considered together.</span></li><li className="flex gap-3"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-primary" /><span><strong className="text-charcoal">Treatment guidance</strong><br />Understand the appropriate direction based on your presentation.</span></li><li className="flex gap-3"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-primary" /><span><strong className="text-charcoal">Next-step plan</strong><br />Leave knowing what the next step should be.</span></li></ul><div className="mt-8 flex flex-col gap-3 sm:flex-row"><BookCTA /><Call /></div></div><div className="rounded-[2rem] border border-border bg-sand p-7 sm:p-9"><img src={assessmentAsset.url} alt="Physiotherapy assessment at LiveFit Physiotherapy" loading="lazy" className="aspect-[4/3] w-full rounded-2xl object-cover" /><div className="mt-7 flex items-end justify-between gap-4"><div><p className="eyebrow text-primary">Assessment</p><p className="mt-2 font-display text-5xl font-bold text-charcoal">{PRICE}</p></div><ClipboardList className="h-10 w-10 text-primary" /></div><p className="mt-3 text-sm leading-6 text-muted-foreground">Book online or call the clinic to arrange your visit.</p></div></div></section>

    <section className="border-y border-border bg-sand"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-24"><div className="max-w-3xl"><Eyebrow>WHY LIVEFIT</Eyebrow><h2 className="mt-5 font-display text-5xl leading-tight sm:text-6xl">Focused care without the guesswork.</h2></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-4"><div className="rounded-2xl border border-border bg-card p-6"><p className="font-display text-3xl text-primary">01</p><h3 className="mt-8 font-semibold">Spine-focused</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Our primary clinical focus is back and spine-related concerns.</p></div><div className="rounded-2xl border border-border bg-card p-6"><p className="font-display text-3xl text-primary">02</p><h3 className="mt-8 font-semibold">Personalized</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Your assessment and next steps are based on your individual presentation.</p></div><div className="rounded-2xl border border-border bg-card p-6"><p className="font-display text-3xl text-primary">03</p><h3 className="mt-8 font-semibold">One-to-one care</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Professional guidance in a dedicated physiotherapy clinic setting.</p></div><div className="rounded-2xl border border-border bg-card p-6"><p className="font-display text-3xl text-primary">04</p><h3 className="mt-8 font-semibold">Central location</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Conveniently located at Pakland Trade Centre, F-7 Markaz, Islamabad.</p></div></div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-28"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><Eyebrow>THE LIVEFIT CLINIC</Eyebrow><h2 className="mt-5 font-display text-5xl leading-tight sm:text-6xl">A professional environment for your care.</h2></div><p className="max-w-lg text-base leading-7 text-muted-foreground">See the assessment, consultation and treatment environment before your visit.</p></div><div className="mt-12 grid gap-5 md:grid-cols-3"><img src={consultAsset.url} alt="Consultation room at LiveFit Physiotherapy" loading="lazy" className="aspect-[4/3] w-full rounded-[1.75rem] object-cover" /><img src={mobilityAsset.url} alt="Mobility physiotherapy at LiveFit" loading="lazy" className="aspect-[4/3] w-full rounded-[1.75rem] object-cover" /><img src={frontAsset.url} alt="LiveFit Physiotherapy clinic in F-7 Markaz Islamabad" loading="lazy" className="aspect-[4/3] w-full rounded-[1.75rem] object-cover" /></div></section>

    <section id="reviews" className="border-y border-border bg-sand"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-24"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><Eyebrow>REAL PATIENT FEEDBACK</Eyebrow><h2 className="mt-5 font-display text-5xl leading-tight sm:text-6xl">What patients say about their experience.</h2></div><div className="flex items-center gap-3 text-sm text-muted-foreground"><span className="text-xl tracking-tight text-primary">★★★★★</span><span>Google reviews</span></div></div><div className="mt-12 flex snap-x gap-5 overflow-x-auto pb-5 [scrollbar-width:none]">{reviews.map((review, i) => <ReviewCard key={review[0]} review={review} index={i} />)}</div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-28"><div className="max-w-3xl"><Eyebrow>HOW IT WORKS</Eyebrow><h2 className="mt-5 font-display text-5xl leading-tight sm:text-6xl">From booking to a clearer plan.</h2></div><div className="mt-12 grid gap-5 md:grid-cols-4"><div className="border-t-2 border-primary pt-6"><span className="font-display text-4xl text-primary">01</span><h3 className="mt-5 text-lg font-semibold">Book</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Choose your assessment time through the booking page.</p></div><div className="border-t-2 border-primary pt-6"><span className="font-display text-4xl text-primary">02</span><h3 className="mt-5 text-lg font-semibold">Meet Dr. Saad</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Discuss your symptoms, concerns and goals.</p></div><div className="border-t-2 border-primary pt-6"><span className="font-display text-4xl text-primary">03</span><h3 className="mt-5 text-lg font-semibold">Understand</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Get a professional assessment of your movement and presentation.</p></div><div className="border-t-2 border-primary pt-6"><span className="font-display text-4xl text-primary">04</span><h3 className="mt-5 text-lg font-semibold">Plan</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Discuss appropriate treatment and next steps.</p></div></div></section>

    <section id="contact" className="border-y border-border bg-sand"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 sm:px-8 lg:grid-cols-[1fr_.9fr] lg:py-24"><div><Eyebrow>VISIT LIVEFIT</Eyebrow><h2 className="mt-5 font-display text-5xl leading-tight sm:text-6xl">Conveniently located in F-7 Markaz.</h2><div className="mt-8 grid gap-5"><div className="flex gap-4"><MapPin className="mt-1 h-5 w-5 shrink-0 text-primary" /><div><p className="font-semibold text-charcoal">Address</p><p className="mt-1 text-sm leading-6 text-muted-foreground">Suite # LG-04, Pakland Trade Centre, F-7 Markaz, Islamabad</p></div></div><div className="flex gap-4"><Clock className="mt-1 h-5 w-5 shrink-0 text-primary" /><div><p className="font-semibold text-charcoal">Clinic Hours</p><p className="mt-1 text-sm leading-6 text-muted-foreground">Monday–Saturday · 12 PM–8 PM<br />Sunday · Closed</p></div></div><div className="flex gap-4"><Phone className="mt-1 h-5 w-5 shrink-0 text-primary" /><div><p className="font-semibold text-charcoal">Phone</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{PHONE_DISPLAY}</p></div></div></div><div className="mt-8 flex flex-col gap-3 sm:flex-row"><BookCTA /><a href={MAPS_URL} target="_blank" rel="noreferrer" className={secondary}><Navigation className="h-4 w-4" /> Get Directions</a></div></div><div className="overflow-hidden rounded-[2rem] border border-border bg-card"><iframe title="LiveFit Physiotherapy location" src="https://www.google.com/maps?q=LiveFit%20Physiotherapy%20F-7%20Markaz%20Islamabad&output=embed" className="h-[380px] w-full border-0 sm:h-[450px]" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /></div></div></section>

    <section id="faq" className="mx-auto max-w-4xl px-5 py-20 sm:px-8 lg:py-28"><div className="text-center"><Eyebrow>QUESTIONS BEFORE YOU BOOK?</Eyebrow><h2 className="mt-5 font-display text-5xl leading-tight sm:text-6xl">Frequently asked questions.</h2></div><div className="mt-10"><Accordion type="single" collapsible className="w-full">{faqs.map(([q, a], i) => <AccordionItem key={q} value={`item-${i}`} className="border-border"><AccordionTrigger className="py-6 text-left text-base font-semibold text-charcoal hover:no-underline">{q}</AccordionTrigger><AccordionContent className="pb-6 text-[15px] leading-7 text-muted-foreground">{a}</AccordionContent></AccordionItem>)}</Accordion></div></section>

    <section className="mx-5 overflow-hidden rounded-[2rem] bg-charcoal sm:mx-8"><div className="mx-auto grid max-w-7xl items-center gap-10 px-6 py-14 sm:px-10 sm:py-16 lg:grid-cols-[1fr_auto] lg:px-14"><div><p className="eyebrow bg-background/10 text-background">BACK PAIN · SCIATICA · DISC BULGE</p><h2 className="mt-5 max-w-3xl font-display text-5xl leading-tight text-background sm:text-6xl">Take the first step toward better movement.</h2><p className="mt-5 max-w-2xl text-base leading-7 text-background/70">Start with a professional physiotherapy assessment at LiveFit Physiotherapy, F-7 Markaz, Islamabad.</p></div><div className="flex flex-col gap-3 lg:min-w-[310px]"><BookCTA /><Call className="border-background/20 bg-background/10 text-background hover:border-background hover:bg-background hover:text-charcoal" /></div></div></section>
  </main>

  <footer className="border-t border-border bg-background"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-12 sm:px-8 md:grid-cols-[1.3fr_.7fr_.7fr]"><div><img src={logo.url} alt="LiveFit Physiotherapy" className="h-12 w-auto object-contain" /><p className="mt-4 max-w-sm text-sm leading-6 text-muted-foreground">Spine-focused physiotherapy for back pain, sciatica, disc-related problems and other movement concerns.</p></div><div><p className="font-semibold text-charcoal">LiveFit Physiotherapy</p><p className="mt-3 text-sm leading-6 text-muted-foreground">F-7 Markaz, Islamabad<br />Mon–Sat · 12 PM–8 PM</p></div><div><p className="font-semibold text-charcoal">Get Started</p><a href="/book-assessment" className="mt-3 block text-sm font-semibold text-primary">Book Assessment</a><a href={PHONE_TEL} className="mt-2 block text-sm text-muted-foreground">Call {PHONE_DISPLAY}</a></div></div><div className="border-t border-border"><div className="mx-auto flex max-w-7xl flex-col gap-2 px-5 py-5 text-xs text-muted-foreground sm:px-8 sm:flex-row sm:justify-between"><span>© {new Date().getFullYear()} LiveFit Physiotherapy. All rights reserved.</span><span>Spine-Focused Physiotherapy · Islamabad</span></div></div></footer>

  <div className="fixed inset-x-0 bottom-0 z-50 border-t border-border bg-card/95 p-3 shadow-2xl backdrop-blur lg:hidden"><div className="mx-auto flex max-w-md gap-2"><BookCTA className="flex-1 px-3 py-3 text-sm" /><a data-track-lead="handled" href={PHONE_TEL} onClick={() => { trackCta("call_click", window.location.pathname, "mobile_sticky_call"); trackPhoneConversion(); }} className="inline-flex items-center justify-center rounded-full border border-border bg-background px-4 py-3 text-charcoal"><Phone className="h-4 w-4" /></a><a data-track-lead="handled" href="/book-assessment" className="inline-flex items-center justify-center rounded-full border border-border bg-background px-4 py-3 text-charcoal" aria-label="Book assessment"><MessageCircle className="h-4 w-4" /></a></div></div>
</div>;
}
