import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Phone, MapPin, Clock, ClipboardList, ArrowRight, HeartPulse, Navigation, MessageCircle, Star } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Header } from "@/components/livefit/Header";
import { trackPhoneConversion } from "@/lib/conversion";
import { trackCta } from "@/lib/track";
import { FAQS, MAPS_URL, PHONE_DISPLAY, PHONE_TEL, SERVICES, STEPS, WHATSAPP } from "@/components/livefit/data";
import logo from "@/assets/livefit-logo.jpg.asset.json";
import doctorAsset from "@/assets/doctor-livefit.png.asset.json";
import assessmentAsset from "@/assets/clinic-assessment.png.asset.json";
import consultAsset from "@/assets/clinic-consult.png.asset.json";
import treatmentAsset from "@/assets/clinic-treatment.png.asset.json";
import mobilityAsset from "@/assets/clinic-mobility.png.asset.json";
import frontAsset from "@/assets/clinic-signboard.webp.asset.json";
import backPainAsset from "@/assets/problem-back-pain.png.asset.json";
import sciaticaAsset from "@/assets/problem-sciatica.png.asset.json";
import discBulgeAsset from "@/assets/problem-disc-bulge.png.asset.json";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "Spine Physiotherapy in Islamabad | LiveFit Physiotherapy" },
      { name: "description", content: "LiveFit Physiotherapy in F-7 Markaz, Islamabad, led by Dr. Saad Sarfraz. Focused physiotherapy for back pain, sciatica and disc bulge. Assessment PKR 1,499." },
      { property: "og:title", content: "Spine Physiotherapy in Islamabad | LiveFit Physiotherapy" },
      { property: "og:description", content: "Dr. Saad Sarfraz provides spine-focused physiotherapy for back pain, sciatica and disc-related problems at LiveFit, Islamabad." },
      { property: "og:type", content: "website" },
      { property: "og:url", content: "https://livefitphysiotherapy.com/" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
    links: [{ rel: "canonical", href: "https://livefitphysiotherapy.com/" }],
    scripts: [{ type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "MedicalClinic", name: "LiveFit Physiotherapy", description: "Physiotherapy clinic in Islamabad focused on back pain, spine problems, sciatica, disc bulge and sports injury rehabilitation.", telephone: "+92 332 3337337", url: "https://livefitphysiotherapy.com/", medicalSpecialty: "Physiotherapy", address: { "@type": "PostalAddress", streetAddress: "Suite # LG-04, Pakland Trade Centre, F-7 Markaz", addressLocality: "Islamabad", addressCountry: "PK" } }) }],
  }),
  component: Index,
});

const PRICE = "PKR 1,499";
const primary = "inline-flex items-center justify-center gap-2.5 rounded-full bg-primary px-6 py-4 text-[15px] font-semibold text-primary-foreground shadow-sm transition-all hover:bg-charcoal hover:text-background hover:-translate-y-0.5";
const secondary = "inline-flex items-center justify-center gap-2.5 rounded-full border border-charcoal/20 bg-card px-6 py-4 text-[15px] font-semibold text-charcoal transition-all hover:border-charcoal hover:bg-charcoal hover:text-background";
const reviews = [
  ["Ifrah Babar","a month ago","It was good clean environment and satisfactory assessment, my father session is going great with them","1 review · 6 photos"],
  ["Abdul Ghaffar","2 months ago","Visited the clinic and very satisfied with the services provided by dr Soma. She is very professional and kind she heard me with patience. She is very competent I would recommend her.","2 reviews"],
  ["Laiba Siddiqui","2 months ago","I highly recommend LiveFit Physio! I came in with severe shoulder, neck, and back pain, and the experience has been amazing. The doctor is incredibly well-qualified, professional, and took the time to guide me through everything thoroughly.","1 review"],
  ["Junaid Nadeem","5 months ago","I had a great experience, Dr.Saad did my complete and detailed examination. I was happy with the session he provided me with and how he guided me with my treatment protocol.","2 reviews"],
  ["Namra Kainat","2 months ago","Had a great experience. I had Cervical stiffness and neck muscle tightness for almost a year and had no idea about about aftr the proper consultation the doctor diagnosed it","4 reviews · 1 photo"],
  ["Md Ali","5 months ago","Extremely professional and trustworthy having a good knowledge and skill in filed. I would recommend livefit physiotherapy the physio to every one","8 reviews"],
  ["Usama Muhammad Nadeem","5 months ago","Dr. Saad is a really passionate physiotherapist. Everyone coming here will be in good hands! ✨","Local Guide · 15 reviews · 4 photos"],
  ["Maryam Nazakat","4 months ago","I came for back stiffness, they recommended dry cupping. My experience was great and I highly recommend this clinic","4 reviews · 6 photos"],
  ["ameer Mukhtar","3 months ago","Dr Saad ko back pain k liye visit kya tha and in 6 session now I'm feeling very much better","1 review"],
  ["Laiba Gul","a month ago","I visited for a consultation and was impressed with a care and the treatment I received.","1 review"],
] as const;
function Eyebrow({ children }: { children: string }) { return <p className="eyebrow inline-flex rounded-full bg-accent px-4 py-2 text-accent-foreground">{children}</p>; }
function WhatsApp({ className = "" }: { className?: string }) { const click = async (e: React.MouseEvent<HTMLAnchorElement>) => { e.preventDefault(); await trackCta("assessment_cta_click", window.location.pathname, "homepage_assessment_cta"); window.location.href = "/book-assessment"; }; return <a data-track-lead="handled" href="/book-assessment" onClick={click} className={`${primary} ${className}`}><ClipboardList className="h-4 w-4" /> Book Your Assessment — {PRICE}</a>; }
function Call({ className = "" }: { className?: string }) { return <a data-track-lead="handled" href={PHONE_TEL} onClick={async e => { e.preventDefault(); await trackCta("call_click", window.location.pathname, "homepage_call"); trackPhoneConversion(); window.location.href = PHONE_TEL; }} className={`${secondary} ${className}`}><Phone className="h-4 w-4" /> Call Now</a>; }
function FlipCard({ title, body, index }: { title: string; body: string; index: number }) { const [flipped, setFlipped] = useState(false); return <button type="button" onClick={() => setFlipped(v => !v)} className="group relative h-56 w-full [perspective:1000px] text-left" aria-label={`${flipped ? "Hide details for" : "Show details for"} ${title}`}><span className={`absolute inset-0 block rounded-3xl transition-transform duration-500 [transform-style:preserve-3d] ${flipped ? "[transform:rotateY(180deg)]" : ""}`}><span className="absolute inset-0 flex flex-col justify-between rounded-3xl border border-border bg-card p-7 [backface-visibility:hidden]"><span className="flex justify-between"><span className="font-display text-4xl text-primary">0{index}</span><ArrowRight className="h-5 w-5 text-muted-foreground" /></span><span><span className="block text-lg font-semibold text-charcoal">{title}</span><span className="mt-2 block text-xs text-muted-foreground">Tap to learn more</span></span></span><span className="absolute inset-0 flex flex-col justify-between rounded-3xl bg-charcoal p-7 text-background [backface-visibility:hidden] [transform:rotateY(180deg)]"><span className="font-display text-3xl text-primary">0{index}</span><span><span className="block text-lg font-semibold">{title}</span><span className="mt-3 block text-sm leading-relaxed text-background/70">{body}</span><span className="mt-5 block text-xs font-semibold text-primary">Book an Assessment →</span></span></span></span></button>; }
function ReviewCard({ review, index }: { review: readonly [string,string,string,string]; index: number }) { const [expanded,setExpanded]=useState(false); const [name,time,text,meta]=review; return <article className={`w-[82vw] shrink-0 snap-start border border-border bg-card p-6 shadow-[0_18px_50px_-34px_oklch(0.24_0.006_150_/_0.5)] sm:w-[420px] ${index%4===0?"sm:mt-5":""} ${index%4===2?"sm:-mt-3":""}`}><div className="flex items-start justify-between gap-4"><div><p className="text-base font-semibold text-charcoal">{name}</p><p className="mt-1 text-xs text-muted-foreground">{time}</p></div><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-accent"><Star className="h-4 w-4 fill-primary text-primary" /></span></div><div className="mt-4 flex gap-0.5 text-sm text-primary" aria-label="5 stars">★★★★★</div><p className={`mt-4 text-[15px] leading-7 text-charcoal-soft ${expanded?"":"line-clamp-5"}`}>&quot;{text}&quot;</p>{text.length>210&&<button type="button" onClick={()=>setExpanded(v=>!v)} className="mt-2 text-sm font-semibold text-primary">{expanded?"Show less":"Read more"}</button>}<p className="mt-5 text-xs text-muted-foreground">{meta}</p><p className="mt-3 text-[11px] font-medium text-muted-foreground">Google review</p></article>; }

function Index() { return <div id="top" className="min-h-screen overflow-x-hidden bg-background"><Header /><main className="pb-20 lg:pb-0">
<section className="relative overflow-hidden"><div aria-hidden className="pointer-events-none absolute -right-40 -top-32 h-[600px] w-[600px] rounded-full bg-accent/70 blur-3xl" /><div className="relative mx-auto grid max-w-7xl items-center gap-10 px-5 py-8 sm:px-8 sm:py-12 lg:grid-cols-[1fr_.92fr] lg:gap-16 lg:py-14"><div className="order-2 lg:order-1"><Eyebrow>SPINE &amp; SPORTS PHYSIOTHERAPY • ISLAMABAD</Eyebrow><h1 className="mt-6 max-w-3xl font-display text-[clamp(2.6rem,8vw,5.2rem)] font-bold leading-[.96] tracking-tight">Back Pain, Sciatica &amp; Disc Bulge.<br /><span className="text-primary">Get the Right Approach.</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-muted-foreground sm:text-lg">Personalized physiotherapy assessment and rehabilitation with Dr. Saad Sarfraz, Chief Physiotherapist at LiveFit.</p><div id="assessment" className="mt-7 max-w-md border border-border bg-card p-6 shadow-[0_24px_60px_-35px_oklch(0.24_0.006_150_/_0.45)] sm:p-7"><p className="eyebrow text-primary">Physiotherapy Assessment</p><p className="mt-2 font-display text-5xl font-bold text-charcoal sm:text-6xl">{PRICE}</p><div className="mt-4 grid gap-2 text-[15px] text-muted-foreground"><span>✓ Personalized Assessment</span><span>✓ Treatment Guidance</span><span>✓ Next-Step Plan</span></div><div className="mt-5 flex flex-col gap-3"><WhatsApp /><Call /></div><p className="mt-4 text-sm text-muted-foreground">F-7 Markaz, Islamabad</p></div></div><div className="relative order-1 lg:order-2 lg:pl-4"><img src={doctorAsset.url} alt="Dr. Saad Sarfraz, Chief Physiotherapist at LiveFit Physiotherapy" width={1080} height={1440} className="aspect-[3/4] w-full rounded-[2rem] object-cover object-top shadow-[0_30px_70px_-28px_oklch(0.24_0.006_150_/_0.45)]" /><div className="absolute bottom-5 left-5 right-5 border border-border/70 bg-card/95 p-5 shadow-xl backdrop-blur sm:left-auto sm:w-[340px]"><p className="text-base font-semibold text-charcoal">Dr. Saad Sarfraz</p><p className="mt-1 text-sm font-semibold text-primary">Chief Physiotherapist</p><p className="mt-2 text-[13px] leading-6 text-muted-foreground">DPT (STMU) · MSPH (QAU)<br />COMT (UK) · CSMT (UK) · CKTP (USA)</p><p className="mt-3 eyebrow text-charcoal">Spine &amp; Sports Physiotherapy</p></div></div></div></section>
<section id="about" className="border-y border-border bg-sand"><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 py-20 sm:px-8 lg:grid-cols-[.7fr_1.3fr] lg:py-24"><div className="relative"><img src={consultAsset.url} alt="Consultation at LiveFit Physiotherapy" loading="lazy" className="aspect-[4/3] w-full object-cover" /></div><div><Eyebrow>Meet Your Physiotherapist</Eyebrow><h2 className="mt-5 font-display text-5xl sm:text-7xl">Dr. Saad Sarfraz</h2><p className="mt-3 text-lg font-semibold text-primary">Chief Physiotherapist</p><p className="mt-5 font-display text-2xl leading-tight text-charcoal sm:text-3xl">Spine &amp; Sports Physiotherapy</p><div className="mt-6 grid gap-2 text-[15px] text-charcoal-soft sm:grid-cols-2"><span>DPT (STMU)</span><span>MSPH (QAU)</span><span>COMT (UK)</span><span>CSMT (UK)</span><span>CKTP (USA)</span></div><p className="mt-7 eyebrow text-primary">Focus Areas: Back Pain · Sciatica · Disc Bulge</p><p className="mt-5 max-w-2xl text-base leading-7 text-muted-foreground">Dr. Saad Sarfraz provides personalized physiotherapy and rehabilitation for patients dealing with back pain, sciatica, disc-related problems and movement limitations.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><WhatsApp /><Call /></div></div></div></section>
<section id="conditions" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-28"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><Eyebrow>The Big Three</Eyebrow><h2 className="mt-5 max-w-3xl font-display text-5xl leading-tight sm:text-6xl">The Problems We Focus On</h2></div><p className="max-w-lg text-base leading-7 text-muted-foreground">Focused assessment and rehabilitation for back pain, sciatica and disc-related conditions.</p></div><div className="mt-12 grid gap-5 md:grid-cols-3">{[["01","Back Pain","Personalized physiotherapy for persistent back pain, stiffness and movement limitations.",backPainAsset.url],["02","Sciatica","Assessment and rehabilitation for back and leg symptoms associated with sciatica.",sciaticaAsset.url],["03","Disc Bulge / Slip Disc","Individualized physiotherapy and rehabilitation for disc-related conditions.",discBulgeAsset.url]].map(([n,t,b,img])=><article key={n} className="group relative min-h-[430px] overflow-hidden bg-charcoal text-background"><img src={img as string} alt={t as string} loading="lazy" className="absolute inset-0 h-full w-full object-cover opacity-40 transition-transform duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-charcoal/55" /><div className="relative flex min-h-[430px] flex-col justify-between p-7 sm:p-8"><span className="font-display text-6xl text-primary">{n}</span><div><h3 className="font-display text-3xl sm:text-4xl">{t}</h3><p className="mt-3 max-w-sm text-[15px] leading-7 text-background/75">{b}</p><a href="#assessment" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-primary">Learn More <ArrowRight className="h-4 w-4" /></a></div></div></article>)}</div></section>
<section className="bg-charcoal text-background"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:px-8 lg:grid-cols-[1fr_.8fr] lg:items-center lg:py-28"><div><Eyebrow>Spine Specialist Focus</Eyebrow><h2 className="mt-6 max-w-3xl font-display text-5xl leading-tight sm:text-7xl">Spine-Focused<br /><span className="text-primary">Physiotherapy.</span></h2><p className="mt-6 max-w-xl text-base leading-7 text-background/70 sm:text-lg">Focused care for people dealing with back pain, sciatica and disc-related problems.</p><div className="mt-9 grid grid-cols-2 gap-4 text-sm font-semibold sm:grid-cols-4"><span>Back</span><span>Spine</span><span>Movement</span><span>Rehabilitation</span></div></div><div className="border-l border-background/15 pl-7 sm:pl-10"><p className="font-display text-3xl">Dr. Saad Sarfraz</p><p className="mt-2 text-sm text-background/60">Chief Physiotherapist</p><div className="mt-8"><WhatsApp /></div></div></div></section>
<section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-28"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr] lg:items-end"><div><Eyebrow>Why Dr. Saad?</Eyebrow><h2 className="mt-5 font-display text-5xl leading-tight sm:text-6xl">Focused. Personal. Clinical.</h2></div><div className="grid gap-7 md:grid-cols-3">{[["01","Spine & Sports Focus","A clear clinical focus on spine-related problems and sports rehabilitation."],["02","Personalized Assessment","Start by understanding your symptoms, movement and functional limitations."],["03","Individualized Rehabilitation","Treatment guidance is shaped around your condition and functional goals."]].map(([n,t,b])=><div key={n} className="border-t border-border pt-5"><p className="font-display text-4xl text-primary">{n}</p><h3 className="mt-5 text-lg font-semibold">{t}</h3><p className="mt-3 text-[15px] leading-7 text-muted-foreground">{b}</p></div>)}</div></div></section>
<section className="mx-auto max-w-7xl px-5 py-10 sm:px-8 lg:py-14"><div className="relative overflow-hidden bg-charcoal px-7 py-10 text-background sm:px-12 lg:px-16 lg:py-14"><div className="relative grid gap-10 lg:grid-cols-[1fr_auto] lg:items-center"><div><Eyebrow>Your First Step Starts Here</Eyebrow><h2 className="mt-5 font-display text-5xl sm:text-6xl">Physiotherapy Assessment</h2><p className="mt-5 max-w-xl text-base leading-7 text-background/70">Start with a professional assessment to understand your symptoms, movement and functional limitations.</p></div><div className="lg:min-w-[300px]"><p className="font-display text-6xl font-bold text-primary">{PRICE}</p><div className="mt-6 flex flex-col gap-3"><WhatsApp /><Call /></div></div></div></div></section>
<section id="services" className="border-y border-border bg-sand"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-28"><div className="max-w-2xl"><Eyebrow>More Than Back &amp; Spine</Eyebrow><h2 className="mt-5 font-display text-4xl sm:text-5xl">More ways we can help</h2><p className="mt-4 text-base leading-7 text-muted-foreground">Specialized physiotherapy and rehabilitation for other movement, injury and recovery needs.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{SERVICES.map((s,i)=><FlipCard key={s.title} title={s.title} body={s.body} index={i+1} />)}</div></div></section>
<section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-28"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><Eyebrow>Real Care. Real Patients.</Eyebrow><h2 className="mt-5 font-display text-4xl sm:text-5xl">Inside the LiveFit approach</h2></div><p className="max-w-md text-base leading-7 text-muted-foreground">A look inside our clinic through genuine assessment, treatment and rehabilitation moments.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[{src:assessmentAsset.url,alt:"Physiotherapy assessment at LiveFit"},{src:treatmentAsset.url,alt:"Treatment session at LiveFit"},{src:mobilityAsset.url,alt:"Mobility session at LiveFit"},{src:frontAsset.url,alt:"LiveFit Physiotherapy clinic in Islamabad"}].map(x=><img key={x.src} src={x.src} alt={x.alt} loading="lazy" className="aspect-[4/5] w-full object-cover" />)}</div></section>
<section id="reviews" className="border-y border-border bg-sand"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-24"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><div className="flex items-center gap-2 text-primary" aria-label="Google reviews"><span className="text-lg">★★★★★</span><span className="eyebrow text-charcoal">Real Google Reviews</span></div><h2 className="mt-5 font-display text-5xl sm:text-6xl">What Our Patients Say</h2><p className="mt-4 max-w-2xl text-base leading-7 text-muted-foreground">Real experiences from patients who have visited LiveFit Physiotherapy.</p></div><div className="hidden text-sm text-muted-foreground sm:block">Swipe to explore reviews →</div></div><div className="mt-12 flex snap-x snap-mandatory gap-5 overflow-x-auto pb-8 pr-5 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{reviews.map((r,i)=><ReviewCard key={`${r[0]}-${i}`} review={r} index={i} />)}</div><div className="mt-8 flex flex-col items-center gap-4 border-t border-border pt-8 text-center"><p className="text-base text-charcoal-soft">Want to experience LiveFit for yourself?</p><WhatsApp /></div></div></section>
<section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-28"><div className="text-center"><Eyebrow>Your Journey</Eyebrow><h2 className="mt-5 font-display text-4xl sm:text-5xl">From Book to Rehabilitation</h2></div><div className="mt-12 grid gap-8 sm:grid-cols-2 lg:grid-cols-4">{STEPS.map(s=><div key={s.n} className="border-t border-border pt-5"><span className="font-display text-4xl text-primary">{s.n}</span><h3 className="mt-4 text-lg font-semibold text-charcoal">{s.title}</h3><p className="mt-2 text-[15px] leading-7 text-muted-foreground">{s.body}</p></div>)}</div><div className="mt-10 flex justify-center"><WhatsApp /></div></section>
<section id="contact" className="border-y border-border bg-sand"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 sm:px-8 lg:grid-cols-[.8fr_1.2fr] lg:py-24"><div><Eyebrow>Visit LiveFit</Eyebrow><h2 className="mt-5 font-display text-5xl leading-tight">LiveFit Physiotherapy<br /><span className="text-primary">F-7 Markaz, Islamabad</span></h2><div className="mt-8 space-y-5 text-[15px] leading-7 text-charcoal"><p className="flex gap-3"><MapPin className="h-5 w-5 shrink-0 text-primary" />Suite # LG-04, Pakland Trade Centre, F-7 Markaz, Islamabad</p><p className="flex gap-3 font-semibold"><Phone className="h-5 w-5 shrink-0 text-primary" /><a href={PHONE_TEL} onClick={trackPhoneConversion}>{PHONE_DISPLAY}</a></p><p className="flex gap-3"><Clock className="h-5 w-5 shrink-0 text-primary" />Monday–Saturday: 12 PM–8 PM<br /><span className="text-muted-foreground">Sunday: Closed</span></p></div><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href={MAPS_URL} target="_blank" rel="noreferrer" className={`${secondary} flex-1`}><Navigation className="h-4 w-4" /> Get Directions</a><Call className="flex-1" /></div></div><div className="min-h-[400px] overflow-hidden border border-border bg-card"><iframe title="LiveFit Physiotherapy location map" src="https://www.google.com/maps?q=Suite%23%20LG-04%2C%20Pakland%20Trade%20Centre%2C%20F7%20Markaz%2C%20Islamabad&output=embed" loading="lazy" className="h-full min-h-[400px] w-full" style={{border:0}} referrerPolicy="no-referrer-when-downgrade" /></div></div></section>
<section className="mx-auto max-w-4xl px-5 py-20 sm:px-8 lg:py-24"><Eyebrow>Questions Before You Book?</Eyebrow><h2 className="mt-5 font-display text-4xl sm:text-5xl">Frequently Asked Questions</h2><Accordion type="single" collapsible className="mt-8 border-t border-border">{FAQS.map(f=><AccordionItem key={f.q} value={f.q}><AccordionTrigger className="py-5 text-left text-base text-charcoal hover:no-underline sm:text-lg">{f.q}</AccordionTrigger><AccordionContent className="pb-6 text-[15px] leading-7 text-muted-foreground">{f.a}</AccordionContent></AccordionItem>)}</Accordion></section>
<section className="bg-charcoal"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-24"><div className="grid gap-10 lg:grid-cols-[1fr_auto] lg:items-center"><div><Eyebrow>Take the Next Step</Eyebrow><h2 className="mt-5 max-w-3xl font-display text-5xl leading-tight text-background sm:text-6xl">Back Pain Shouldn't<br /><span className="text-primary">Control Your Day.</span></h2><p className="mt-5 max-w-xl text-base leading-7 text-background/70">Start with a professional physiotherapy assessment at LiveFit.</p></div><div><p className="font-display text-6xl font-bold text-primary">{PRICE}</p><p className="mt-2 text-sm text-background/60">Physiotherapy Assessment</p><div className="mt-6 flex flex-col gap-3"><WhatsApp /><Call /></div></div></div></div></section>
<footer className="border-t border-border bg-sand"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-14 sm:px-8 md:grid-cols-2 lg:grid-cols-4"><div><div className="flex items-center gap-3"><img src={logo.url} alt="LiveFit Physiotherapy logo" width={44} height={44} className="h-11 w-11 rounded-sm object-cover mix-blend-multiply" /><div><p className="font-display text-xl">LiveFit</p><p className="eyebrow text-muted-foreground">Physiotherapy</p></div></div><p className="mt-5 text-[15px] leading-7 text-muted-foreground">Spine &amp; Sports Physiotherapy<br />F-7 Markaz, Islamabad</p></div><div><p className="eyebrow text-charcoal">Quick Links</p><ul className="mt-5 space-y-3 text-[15px] text-muted-foreground"><li><a href="#top">Home</a></li><li><a href="#about">About Dr. Saad</a></li><li><a href="#conditions">Conditions</a></li><li><a href="#services">Services</a></li><li><a href="#reviews">Reviews</a></li><li><a href="#contact">Contact</a></li></ul></div><div><p className="eyebrow text-charcoal">Services</p><ul className="mt-5 space-y-3 text-[15px] text-muted-foreground"><li>Back Pain</li><li>Sciatica</li><li>Disc Bulge</li><li>Spine Physiotherapy</li><li>Sports Rehabilitation</li><li>Joint &amp; Mobility</li></ul></div><div><p className="eyebrow text-charcoal">Contact</p><a href={PHONE_TEL} onClick={trackPhoneConversion} className="mt-5 block text-lg font-semibold text-charcoal">{PHONE_DISPLAY}</a><p className="mt-3 text-[15px] leading-7 text-muted-foreground">Monday–Saturday: 12 PM–8 PM<br />Sunday: Closed</p><div className="mt-5"><WhatsApp /></div></div></div><div className="mx-auto max-w-7xl border-t border-border px-5 py-5 text-xs text-muted-foreground">© 2026 LiveFit Physiotherapy. All Rights Reserved.</div></footer>
</main><div className="fixed inset-x-0 bottom-0 z-50 grid grid-cols-2 gap-2 border-t border-border bg-card/95 p-2 shadow-[0_-8px_24px_-16px_oklch(0.24_0.006_150_/_0.4)] backdrop-blur lg:hidden"><a href={WHATSAPP} target="_blank" rel="noreferrer" onClick={() => void trackCta("whatsapp_click", window.location.pathname, "mobile_sticky_whatsapp")} className="flex items-center justify-center gap-2 rounded-full bg-primary py-3.5 text-sm font-semibold text-primary-foreground"><MessageCircle className="h-4 w-4" /> WhatsApp</a><a href={PHONE_TEL} onClick={async e=>{e.preventDefault();await trackCta("call_click",window.location.pathname,"mobile_sticky_call");trackPhoneConversion();window.location.href=PHONE_TEL}} className="flex items-center justify-center gap-2 rounded-full bg-charcoal py-3.5 text-sm font-semibold text-background"><Phone className="h-4 w-4" /> Call {PHONE_DISPLAY}</a></div></div>; }
