/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is automatically generated by TanStack Router.
// It is kept in sync here so the existing repository can type-check before the router plugin regenerates it.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as OtherServicesRouteImport } from './routes/other-services'
import { Route as AboutDrSaadRouteImport } from './routes/about-dr-saad'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as BookAssessmentRouteImport } from './routes/book-assessment'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const OwnerRoute = OwnerRouteImport.update({ id: '/owner', path: '/owner', getParentRoute: () => rootRouteImport } as any)
const OtherServicesRoute = OtherServicesRouteImport.update({ id: '/other-services', path: '/other-services', getParentRoute: () => rootRouteImport } as any)
const AboutDrSaadRoute = AboutDrSaadRouteImport.update({ id: '/about-dr-saad', path: '/about-dr-saad', getParentRoute: () => rootRouteImport } as any)
const ReviewsRoute = ReviewsRouteImport.update({ id: '/reviews', path: '/reviews', getParentRoute: () => rootRouteImport } as any)
const BookAssessmentRoute = BookAssessmentRouteImport.update({ id: '/book-assessment', path: '/book-assessment', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath { '/': typeof IndexRoute; '/owner': typeof OwnerRoute; '/other-services': typeof OtherServicesRoute; '/about-dr-saad': typeof AboutDrSaadRoute; '/reviews': typeof ReviewsRoute; '/book-assessment': typeof BookAssessmentRoute }
export interface FileRoutesByTo { '/': typeof IndexRoute; '/owner': typeof OwnerRoute; '/other-services': typeof OtherServicesRoute; '/about-dr-saad': typeof AboutDrSaadRoute; '/reviews': typeof ReviewsRoute; '/book-assessment': typeof BookAssessmentRoute }
export interface FileRoutesById { __root__: typeof rootRouteImport; '/': typeof IndexRoute; '/owner': typeof OwnerRoute; '/other-services': typeof OtherServicesRoute; '/about-dr-saad': typeof AboutDrSaadRoute; '/reviews': typeof ReviewsRoute; '/book-assessment': typeof BookAssessmentRoute }
export interface FileRouteTypes { fileRoutesByFullPath: FileRoutesByFullPath; fullPaths: '/' | '/owner' | '/other-services' | '/about-dr-saad' | '/reviews' | '/book-assessment'; fileRoutesByTo: FileRoutesByTo; to: '/' | '/owner' | '/other-services' | '/about-dr-saad' | '/reviews' | '/book-assessment'; id: '__root__' | '/' | '/owner' | '/other-services' | '/about-dr-saad' | '/reviews' | '/book-assessment'; fileRoutesById: FileRoutesById }
export interface RootRouteChildren { IndexRoute: typeof IndexRoute; OwnerRoute: typeof OwnerRoute; OtherServicesRoute: typeof OtherServicesRoute; AboutDrSaadRoute: typeof AboutDrSaadRoute; ReviewsRoute: typeof ReviewsRoute; BookAssessmentRoute: typeof BookAssessmentRoute }

declare module '@tanstack/react-router' {
 interface FileRoutesByPath {
  '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
  '/owner': { id: '/owner'; path: '/owner'; fullPath: '/owner'; preLoaderRoute: typeof OwnerRouteImport; parentRoute: typeof rootRouteImport }
  '/other-services': { id: '/other-services'; path: '/other-services'; fullPath: '/other-services'; preLoaderRoute: typeof OtherServicesRouteImport; parentRoute: typeof rootRouteImport }
  '/about-dr-saad': { id: '/about-dr-saad'; path: '/about-dr-saad'; fullPath: '/about-dr-saad'; preLoaderRoute: typeof AboutDrSaadRouteImport; parentRoute: typeof rootRouteImport }
  '/reviews': { id: '/reviews'; path: '/reviews'; fullPath: '/reviews'; preLoaderRoute: typeof ReviewsRouteImport; parentRoute: typeof rootRouteImport }
  '/book-assessment': { id: '/book-assessment'; path: '/book-assessment'; fullPath: '/book-assessment'; preLoaderRoute: typeof BookAssessmentRouteImport; parentRoute: typeof rootRouteImport }
 }
}

const rootRouteChildren: RootRouteChildren = { IndexRoute, OwnerRoute, OtherServicesRoute, AboutDrSaadRoute, ReviewsRoute, BookAssessmentRoute }
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' { interface Register { ssr: true; router: Awaited<ReturnType<typeof getRouter>>; config: Awaited<ReturnType<typeof startInstance.getOptions>> } }
