/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutDrSaadRouteImport } from './routes/about-dr-saad'
import { Route as BackPainPhysiotherapyIslamabadRouteImport } from './routes/back-pain-physiotherapy-islamabad'
import { Route as BookAssessmentRouteImport } from './routes/book-assessment'
import { Route as DiscBulgePhysiotherapyIslamabadRouteImport } from './routes/disc-bulge-physiotherapy-islamabad'
import { Route as OtherServicesRouteImport } from './routes/other-services'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as SciaticaPhysiotherapyIslamabadRouteImport } from './routes/sciatica-physiotherapy-islamabad'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardLoginRouteImport } from './routes/dashboard.login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutDrSaadRoute = AboutDrSaadRouteImport.update({
  id: '/about-dr-saad',
  path: '/about-dr-saad',
  getParentRoute: () => rootRouteImport,
} as any)
const BackPainPhysiotherapyIslamabadRoute =
  BackPainPhysiotherapyIslamabadRouteImport.update({
    id: '/back-pain-physiotherapy-islamabad',
    path: '/back-pain-physiotherapy-islamabad',
    getParentRoute: () => rootRouteImport,
  } as any)
const BookAssessmentRoute = BookAssessmentRouteImport.update({
  id: '/book-assessment',
  path: '/book-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscBulgePhysiotherapyIslamabadRoute =
  DiscBulgePhysiotherapyIslamabadRouteImport.update({
    id: '/disc-bulge-physiotherapy-islamabad',
    path: '/disc-bulge-physiotherapy-islamabad',
    getParentRoute: () => rootRouteImport,
  } as any)
const OtherServicesRoute = OtherServicesRouteImport.update({
  id: '/other-services',
  path: '/other-services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SciaticaPhysiotherapyIslamabadRoute =
  SciaticaPhysiotherapyIslamabadRouteImport.update({
    id: '/sciatica-physiotherapy-islamabad',
    path: '/sciatica-physiotherapy-islamabad',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLoginRoute = DashboardLoginRouteImport.update({
  id: '/dashboard/login',
  path: '/dashboard/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-dr-saad': typeof AboutDrSaadRoute
  '/back-pain-physiotherapy-islamabad': typeof BackPainPhysiotherapyIslamabadRoute
  '/book-assessment': typeof BookAssessmentRoute
  '/disc-bulge-physiotherapy-islamabad': typeof DiscBulgePhysiotherapyIslamabadRoute
  '/other-services': typeof OtherServicesRoute
  '/reviews': typeof ReviewsRoute
  '/sciatica-physiotherapy-islamabad': typeof SciaticaPhysiotherapyIslamabadRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-dr-saad': typeof AboutDrSaadRoute
  '/back-pain-physiotherapy-islamabad': typeof BackPainPhysiotherapyIslamabadRoute
  '/book-assessment': typeof BookAssessmentRoute
  '/disc-bulge-physiotherapy-islamabad': typeof DiscBulgePhysiotherapyIslamabadRoute
  '/other-services': typeof OtherServicesRoute
  '/reviews': typeof ReviewsRoute
  '/sciatica-physiotherapy-islamabad': typeof SciaticaPhysiotherapyIslamabadRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-dr-saad': typeof AboutDrSaadRoute
  '/back-pain-physiotherapy-islamabad': typeof BackPainPhysiotherapyIslamabadRoute
  '/book-assessment': typeof BookAssessmentRoute
  '/disc-bulge-physiotherapy-islamabad': typeof DiscBulgePhysiotherapyIslamabadRoute
  '/other-services': typeof OtherServicesRoute
  '/reviews': typeof ReviewsRoute
  '/sciatica-physiotherapy-islamabad': typeof SciaticaPhysiotherapyIslamabadRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-dr-saad'
    | '/back-pain-physiotherapy-islamabad'
    | '/book-assessment'
    | '/disc-bulge-physiotherapy-islamabad'
    | '/other-services'
    | '/reviews'
    | '/sciatica-physiotherapy-islamabad'
    | '/dashboard/login'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-dr-saad'
    | '/back-pain-physiotherapy-islamabad'
    | '/book-assessment'
    | '/disc-bulge-physiotherapy-islamabad'
    | '/other-services'
    | '/reviews'
    | '/sciatica-physiotherapy-islamabad'
    | '/dashboard/login'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about-dr-saad'
    | '/back-pain-physiotherapy-islamabad'
    | '/book-assessment'
    | '/disc-bulge-physiotherapy-islamabad'
    | '/other-services'
    | '/reviews'
    | '/sciatica-physiotherapy-islamabad'
    | '/dashboard/login'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutDrSaadRoute: typeof AboutDrSaadRoute
  BackPainPhysiotherapyIslamabadRoute: typeof BackPainPhysiotherapyIslamabadRoute
  BookAssessmentRoute: typeof BookAssessmentRoute
  DiscBulgePhysiotherapyIslamabadRoute: typeof DiscBulgePhysiotherapyIslamabadRoute
  OtherServicesRoute: typeof OtherServicesRoute
  ReviewsRoute: typeof ReviewsRoute
  SciaticaPhysiotherapyIslamabadRoute: typeof SciaticaPhysiotherapyIslamabadRoute
  DashboardLoginRoute: typeof DashboardLoginRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-dr-saad': {
      id: '/about-dr-saad'
      path: '/about-dr-saad'
      fullPath: '/about-dr-saad'
      preLoaderRoute: typeof AboutDrSaadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/back-pain-physiotherapy-islamabad': {
      id: '/back-pain-physiotherapy-islamabad'
      path: '/back-pain-physiotherapy-islamabad'
      fullPath: '/back-pain-physiotherapy-islamabad'
      preLoaderRoute: typeof BackPainPhysiotherapyIslamabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-assessment': {
      id: '/book-assessment'
      path: '/book-assessment'
      fullPath: '/book-assessment'
      preLoaderRoute: typeof BookAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disc-bulge-physiotherapy-islamabad': {
      id: '/disc-bulge-physiotherapy-islamabad'
      path: '/disc-bulge-physiotherapy-islamabad'
      fullPath: '/disc-bulge-physiotherapy-islamabad'
      preLoaderRoute: typeof DiscBulgePhysiotherapyIslamabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/other-services': {
      id: '/other-services'
      path: '/other-services'
      fullPath: '/other-services'
      preLoaderRoute: typeof OtherServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sciatica-physiotherapy-islamabad': {
      id: '/sciatica-physiotherapy-islamabad'
      path: '/sciatica-physiotherapy-islamabad'
      fullPath: '/sciatica-physiotherapy-islamabad'
      preLoaderRoute: typeof SciaticaPhysiotherapyIslamabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/login': {
      id: '/dashboard/login'
      path: '/dashboard/login'
      fullPath: '/dashboard/login'
      preLoaderRoute: typeof DashboardLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutDrSaadRoute: AboutDrSaadRoute,
  BackPainPhysiotherapyIslamabadRoute: BackPainPhysiotherapyIslamabadRoute,
  BookAssessmentRoute: BookAssessmentRoute,
  DiscBulgePhysiotherapyIslamabadRoute: DiscBulgePhysiotherapyIslamabadRoute,
  OtherServicesRoute: OtherServicesRoute,
  ReviewsRoute: ReviewsRoute,
  SciaticaPhysiotherapyIslamabadRoute: SciaticaPhysiotherapyIslamabadRoute,
  DashboardLoginRoute: DashboardLoginRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
